<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
      <AssemblyName>Thales.OPCUAClient.UAClient</AssemblyName>
      <RootNamespace>Thales.OPCUAClient.UAClient</RootNamespace>
      <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
      <Version>1.5.0</Version>
      <Company>Thales</Company>
      <Copyright>Copyright Thales ©2025</Copyright>
      <BaseOutputPath>..\output\OPCUAClient\</BaseOutputPath>
      <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

    <ItemGroup>
        <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua" Version="1.5.376.213" />
        <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Core" Version="1.5.376.213" />
        <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Configuration" Version="1.5.376.213" />
        <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Security.Certificates" Version="1.5.376.213" />
        <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client" Version="1.5.376.213" />
        <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client.ComplexTypes" Version="1.5.376.213" />

        <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.4" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.4" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.4" />
        <PackageReference Include="Splat" Version="17.1.1" />
        <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.8" />
        <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
        <PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.18" />

        <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    </ItemGroup>

</Project>
